[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$VideoRoot,

    [string]$RepoRoot,

    [string]$HermesRoot = $(if ($env:LOCALAPPDATA) { Join-Path $env:LOCALAPPDATA 'hermes' } else { '' }),

    [string]$FfmpegBin,

    [string]$FfprobeBin,

    [switch]$Apply
)

$ErrorActionPreference = 'Stop'

function Resolve-RequiredPath {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Name,
        [ValidateSet('File', 'Directory')][string]$Type = 'File'
    )

    if ([string]::IsNullOrWhiteSpace($Path)) {
        throw "$Name is required."
    }
    $absolute = [System.IO.Path]::GetFullPath($Path)
    $pathType = if ($Type -eq 'Directory') { 'Container' } else { 'Leaf' }
    if (!(Test-Path -LiteralPath $absolute -PathType $pathType)) {
        throw "$Name was not found: $absolute"
    }
    if ([System.IO.Path]::GetPathRoot($absolute) -eq $absolute) {
        return $absolute
    }
    return $absolute.TrimEnd('\')
}

if ([string]::IsNullOrWhiteSpace($RepoRoot)) {
    $RepoRoot = (Get-Item -LiteralPath $PSScriptRoot).Parent.Parent.Parent.Parent.FullName
}

$repo = Resolve-RequiredPath -Path $RepoRoot -Name 'RepoRoot' -Type Directory
$video = Resolve-RequiredPath -Path $VideoRoot -Name 'VideoRoot' -Type Directory
$hermes = Resolve-RequiredPath -Path $HermesRoot -Name 'HermesRoot' -Type Directory
$node = Resolve-RequiredPath -Path (Join-Path $hermes 'node\node.exe') -Name 'Hermes Node' -Type File
$entry = Resolve-RequiredPath -Path (Join-Path $repo 'src\index.js') -Name 'highlight_local entrypoint' -Type File

if ([string]::IsNullOrWhiteSpace($FfmpegBin)) {
    $FfmpegBin = Join-Path $repo 'tools\bin\ffmpeg.exe'
}
if ([string]::IsNullOrWhiteSpace($FfprobeBin)) {
    $FfprobeBin = Join-Path $repo 'tools\bin\ffprobe.exe'
}
$ffmpeg = Resolve-RequiredPath -Path $FfmpegBin -Name 'FFmpeg' -Type File
$ffprobe = Resolve-RequiredPath -Path $FfprobeBin -Name 'FFprobe' -Type File
$ytdlp = Resolve-RequiredPath -Path (Join-Path $repo 'tools\bin\yt-dlp.exe') -Name 'yt-dlp' -Type File

$nodeModules = Join-Path $hermes 'node\node_modules'
$videoContextEntry = Resolve-RequiredPath -Path (Join-Path $nodeModules '@smallthinkingmachines\video-context-mcp\dist\index.js') -Name 'video_context entrypoint' -Type File
$premiereEntry = Resolve-RequiredPath -Path (Join-Path $nodeModules 'adobe-premiere-pro-mcp\dist\index.js') -Name 'premiere_cep entrypoint' -Type File
$transformersRuntime = Resolve-RequiredPath -Path (Join-Path $nodeModules '@smallthinkingmachines\video-context-mcp\vendor\transformers.node.min.mjs') -Name 'local Transformers runtime' -Type File

$cacheRoot = Join-Path $repo '.cache'
$videoCache = Join-Path $cacheRoot 'video-context-mcp'
$highlightCache = Join-Path $cacheRoot 'highlight-mcp'
$asrCache = Join-Path $videoCache 'transformers'
$premiereTemp = Join-Path $env:LOCALAPPDATA 'Temp\premiere-mcp-bridge'
$configPath = Join-Path $repo '.codex\config.toml'

$managedBlock = @"
# BEGIN local-livestream-premiere managed MCP block
# Generated by hermes-skills/media/local-livestream-premiere/scripts/ensure-hermes-config.ps1

[mcp_servers.video_context]
command = '$node'
args = ['$videoContextEntry']
cwd = '$repo'
startup_timeout_sec = 30
tool_timeout_sec = 900
default_tools_approval_mode = 'writes'

[mcp_servers.video_context.env]
VCM_TOOLCHAIN_MODE = 'system'
VCM_FFMPEG_BIN = '$ffmpeg'
VCM_FFPROBE_BIN = '$ffprobe'
VCM_YTDLP_BIN = '$ytdlp'
VCM_CACHE_DIR = '$videoCache'
VCM_OCR_BACKEND = 'wasm'
VCM_ASR_BACKEND = 'transformers'

[mcp_servers.highlight_local]
command = '$node'
args = ['$entry']
cwd = '$repo'
startup_timeout_sec = 30
tool_timeout_sec = 3600
default_tools_approval_mode = 'writes'

[mcp_servers.highlight_local.env]
HIGHLIGHT_PROJECT_ROOT = '$repo'
HIGHLIGHT_ALLOWED_ROOTS = '$repo;$video'
HIGHLIGHT_FFMPEG_BIN = '$ffmpeg'
HIGHLIGHT_FFPROBE_BIN = '$ffprobe'
HIGHLIGHT_CACHE_DIR = '$highlightCache'
HIGHLIGHT_ASR_MODE = 'auto'
HIGHLIGHT_ASR_CACHE_DIR = '$asrCache'
HIGHLIGHT_TRANSFORMERS_RUNTIME = '$transformersRuntime'
HIGHLIGHT_MOTION_ENABLED = 'true'
HIGHLIGHT_MOTION_SAMPLE_RATE = '1'
HIGHLIGHT_MOTION_DIFF_THRESHOLD = '0.08'

[mcp_servers.premiere_cep]
command = '$node'
args = ['$premiereEntry']
cwd = '$repo'
startup_timeout_sec = 30
tool_timeout_sec = 300
default_tools_approval_mode = 'writes'

[mcp_servers.premiere_cep.env]
PREMIERE_TEMP_DIR = '$premiereTemp'

# END local-livestream-premiere managed MCP block
"@.Trim()

function Remove-ManagedServerSections {
    param([string]$Text)

    $lines = $Text -split "`r?`n"
    $kept = New-Object System.Collections.Generic.List[string]
    $skip = $false
    foreach ($line in $lines) {
        if ($line -match '^\s*\[mcp_servers\.(video_context|highlight_local|premiere_cep)(?:\.|\])') {
            $skip = $true
            continue
        }
        if ($skip -and $line -match '^\s*\[') {
            $skip = $false
        }
        if (!$skip) {
            [void]$kept.Add($line)
        }
    }
    return ($kept -join "`r`n").Trim()
}

$existing = ''
if (Test-Path -LiteralPath $configPath -PathType Leaf) {
    $existing = Get-Content -LiteralPath $configPath -Raw
}
$withoutManaged = Remove-ManagedServerSections -Text $existing
$withoutManaged = [regex]::Replace($withoutManaged, '(?ms)^# BEGIN local-livestream-premiere managed MCP block\r?\n.*?^# END local-livestream-premiere managed MCP block\s*', '').Trim()
$finalConfig = if ($withoutManaged) { "$withoutManaged`r`n`r`n$managedBlock`r`n" } else { "$managedBlock`r`n" }

Write-Output "RepoRoot: $repo"
Write-Output "VideoRoot: $video"
Write-Output "Hermes config: $configPath"
Write-Output "Servers: video_context, highlight_local, premiere_cep"
Write-Output "Mode: $(if ($Apply) { 'apply' } else { 'preview' })"

if (!$Apply) {
    Write-Output 'Preview only. Re-run with -Apply to back up and write the project-scoped config.'
    Write-Output $finalConfig
    exit 0
}

$configDirectory = Split-Path -Parent $configPath
New-Item -ItemType Directory -Path $configDirectory -Force | Out-Null
if (Test-Path -LiteralPath $configPath -PathType Leaf) {
    $stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
    $backupPath = "$configPath.bak-$stamp"
    Copy-Item -LiteralPath $configPath -Destination $backupPath -Force
    Write-Output "Backup: $backupPath"
}
[System.IO.File]::WriteAllText($configPath, $finalConfig, [System.Text.UTF8Encoding]::new($false))
Write-Output "Wrote: $configPath"
Write-Output 'Restart Hermes or start a new session, then run: hermes mcp list'
